app.py
from flask import Flask
import db
from routes.home import home_bp
from routes.classic import classic_bp

app = Flask(__name__)
app.secret_key = 'supersecretkey'
db.create_tables()

app.register_blueprint(home_bp)

app.register_blueprint(classic_bp)

if __name__ == '__main__':
    app.run(debug = True)

routes/classic.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
import db
import random
import char

classic_bp = Blueprint('classic', __name__)

no_of_chars = db.number_of_characters()

names = []
mistakeColors = []
found = False

# Classic game loop
@classic_bp.route('/classic', methods=['POST','GET'])
def classic():

    global found

    if request.method == 'POST':
        if request.form['name'] not in names:
            if (db.check_name_in_database(request.form['name']) and not found):
                names.insert(0,request.form['name'])
                mName = char.check_name(session['current_char'], db.get_characterID(request.form['name']))
                mGender = char.check_gender(session['current_char'], db.get_characterID(request.form['name']))
                mA = char.check_affiliation(session['current_char'], db.get_characterID(request.form['name']))
                mResidence = char.check_residence(session['current_char'], db.get_characterID(request.form['name']))
                mStatus = char.check_status(session['current_char'], db.get_characterID(request.form['name']))
                mTK = char.check_TK(session['current_char'], db.get_characterID(request.form['name']))
                mTP = char.check_TP(session['current_char'], db.get_characterID(request.form['name']))
                mDebut = char.check_debut(session['current_char'], db.get_characterID(request.form['name']))

                mistakeColors.insert(0,(mName,mGender,mA,mResidence, mStatus,mTK,mTP,mDebut))
            if (session['current_char'] == db.get_characterID(names[0])):
                found = True
            else:
                found = False



    print(names)
    print(mistakeColors)
    
    rows = db.get_all_saved_characters(names)
    namesCount = len(names)
    
    return render_template('classic.html', characters=rows, found=found,mistakeColors=mistakeColors, score=namesCount)

#Starting or reseting a game
@classic_bp.route('/classic/start', methods=['POST','GET'])
def start_game():

    global found 

    session['current_char'] = random.randint(1,no_of_chars)
    print('Current char: ', session['current_char'] )
    
    names.clear()
    mistakeColors.clear()
    found = False
    return redirect(url_for('classic.classic'))

routes/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def home():
    return render_template('home.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <header>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('home.home') }}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('classic.start_game') }}">Classic</a></li>
    </header>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block main %}
    {% endblock %}
</body>
</html>

templates/classic.html
{% extends  'base.html' %}


{% block head %}
    <title>AOTODLE - Classic</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/classic.css') }}">
{% endblock %}


{% block main %}
    <div class="container">
        <h1> Classic </h1>
        <p> work in progress
        </p>
        <form action="/classic" method="POST" style="margin: 0;">
            <input type="text" name="name" required>
            <button type="submit"> Enter </button>
        </form>

        {% if found %}
            <h1>CHAR IS FOUND</h1>
            {% if score > 1 %}
                <h2>Took you {{score}} tries</h2>
            {% else %}
                <h2>Took you {{score}} try</h2>
            {% endif %}
            <form action="/classic/start" method="POST" style="margin: 0;">
                <button type="submit"> Restart </button>
            </form>
        {% endif %}
    </div>

    <div class="game_window">
        
        <table border="2">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Affiliation1</th>
                    <th>Affiliation2</th>
                    <th>Residence</th>
                    <th>Status</th>
                    <th>TitanKills</th>
                    <th>TitanPowers</th>
                    <th>Debut</th>
                </tr>
            </thead>
            <tbody>
                {% for character in characters %}
                <tr>
                    <td><img src="{{url_for('static', filename=character[10].split('static/')[1])}}" class="character_image" /></td>
                    <td style="background-color: {{mistakeColors[loop.index - 1][0]}};"> {{ character[1] }}</td>
                    {% if character[2] %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][1]}};"> Female </td>
                    {% else %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][1]}};"> Male</td>
                    {% endif %}
                    <td style="background-color: {{mistakeColors[loop.index - 1][2][0]}};">{{ character[3] }}</td>
                    <td style="background-color: {{mistakeColors[loop.index - 1][2][1]}};">{{ character[4] }}</td>
                    <td style="background-color: {{mistakeColors[loop.index - 1][3]}};">{{ character[5] }}</td>
                    {% if character[6] %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][4]}};"> Alive </td>
                    {% else %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][4]}};"> Dead </td>
                    {% endif %}

                    {% if mistakeColors[loop.index - 1][5] == 'up' %}
                        <td style="background-color: red;">{{ character[7] }}</td>
                    {% elif mistakeColors[loop.index - 1][5] == 'down' %}
                        <td style="background-color: maroon;">{{ character[7] }}</td>
                    {% else %}
                        <td style="background-color: green;">{{ character[7] }}</td>
                    {% endif %}

                    {% if character[8] %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][6]}};"> Yes </td>
                    {% else %}
                        <td style="background-color: {{mistakeColors[loop.index - 1][6]}};"> No </td>
                    {% endif %}

                    {% if mistakeColors[loop.index - 1][7] == 'up' %}
                        <td style="background-color: red;">{{ character[9] }}</td>
                    {% elif mistakeColors[loop.index - 1][7] == 'down' %}
                        <td style="background-color: maroon;">{{ character[9] }}</td>
                    {% else %}
                        <td style="background-color: green;">{{ character[9] }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
      
{% endblock %}

templates/home.html
{% extends  'base.html' %}


{% block head %}
    <title>AOTODLE</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}


{% block main %}
    <div class="container">
        <h1> Welcome to this new game </h1>
        <p> This is a work in progress <br> 
            Feel free to not judge!
        </p>
    </div>
      
{% endblock %}